version: "3.7"

services:
    database:
        image: postgres
        container_name: typeorm
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=app
        volumes:
            -   pgdata:/data/postgres 
    app:
        build: .
        container_name: rentx
        ports:
            - "3333:3333"
        volumes:
            -   .:/usr/app
        links:
            -   database
        depends_on:
            -   database    
                
volumes:
    pgdata: 
        driver: local